# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer_Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='comision',
            name='pedido',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='nombre',
            new_name='calle',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='lector',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Region'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Direccion'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Ciudad'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editorial',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Direccion'),
        ),
        migrations.AddField(
            model_name='lector',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Direccion'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='correo',
            field=models.EmailField(default=b'', max_length=254),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='correo',
            field=models.EmailField(default=b'', max_length=254),
        ),
        migrations.AlterField(
            model_name='lector',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Editorial'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Genero'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Dealer'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Dealer'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Lector'),
        ),
        migrations.DeleteModel(
            name='Comision',
        ),
        migrations.AddField(
            model_name='pedido_libro',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Libro'),
        ),
        migrations.AddField(
            model_name='pedido_libro',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Pedido'),
        ),
        migrations.AddField(
            model_name='pedido_lector',
            name='lector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Lector'),
        ),
        migrations.AddField(
            model_name='pedido_lector',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Pedido'),
        ),
        migrations.AddField(
            model_name='dealer_catalogo',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Dealer'),
        ),
        migrations.AddField(
            model_name='dealer_catalogo',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Libro'),
        ),
    ]
