# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20171025_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='lugar',
        ),
    ]
