# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_dealer_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='lugar',
        ),
    ]
