# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_editorial_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
