# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_libro_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagenURL',
            field=models.TextField(default=b''),
        ),
    ]
