# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_libro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='ventas',
            field=models.IntegerField(default=0),
        ),
    ]
