# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_genero_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='venta',
            field=models.IntegerField(default=0),
        ),
    ]
